// User
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

// Services
export const SERVICES_LOADING_TRUE = 'SERVICES_LOADING_TRUE';
export const SERVICES_LOADING_FALSE = 'SERVICES_LOADING_FALSE';
export const ALL_SERVICES_GET = 'ALL_SERVICES_GET';
export const ALL_SERVICES_GET_ERROR = 'ALL_SERVICES_GET_ERROR';
export const SERVICE_INFO_GET = 'SERVICE_INFO_GET';
export const SERVICE_INFO_ERROR = 'SERVICE_INFO_ERROR';

// Maintenance
export const ALL_MAINTENANCES_GET = 'ALL_MAINTENANCES_GET';
export const ALL_MAINTENANCES_GET_ERROR = 'ALL_MAINTENANCES_GET_ERROR';
